config/routes.rb
Rails.application.routes.draw do
  devise_for :models

  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/sign_in' => 'devise/sessions#new'
  end


  resources :comment

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
  # get '/posts', to: 'posts#index', as: :posts
  # get '/posts/new', to: 'posts#new', as: :new_post
  # get '/posts/:id', to: 'posts#show', as: :post
  # post '/posts', to: 'posts#create'
  # get '/posts/:id/edit', to: 'posts#edit', as: :edit_post
  # patch '/posts/:id', to: 'posts#update'
  # delete '/posts/:id', to: 'posts#delete'
    post 'comments', to: 'comment#create'
  end

  get '/categories/:category_handle/posts', to: 'posts#index', as: :category_posts

  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :nullify

  def self.find_by_handle(handle)
    find_by(handle: handle)
  end

  def self.find_by_handle!(handle)
    find_by_handle(handle) ||
        raise(ActiveRecord::RecordNotFound)
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  has_many :comments

    #scope :ordered, -> { order(created_at: :desc) }
    scope :ordered, -> { order(id: :desc) }
    scope :with_categories, -> { includes(:category) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments

  def username
    return email.split('@')[0].capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  before_action :set_post
  before_action :authenticate_user!

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_back(fallback_location: root_path)
  end

  private
  def comment_params
    params.require(:comment).permit(:username, :body)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :load_categories
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if params[:category_handle]
      @category = Category.find_by_handle!(params[:category_handle])
      @posts = @category.posts.ordered.with_categories
    end
    @posts ||= Post.ordered.with_categories
  end

  def load_categories
    @categories = Category.all
  end

  def show
    load_post
    @comment = Comment.new
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new
    @post.update(post_params)
    redirect_to @post
  end

  def edit
    load_post
  end

  def update
    load_post
    @post.update(post_params)
    redirect_to :post
  end

  def delete
    load_post
    @post.destroy
    redirect_to :posts
  end

  private
  def post_params
    params.require(:post).permit(:title, :text, :category_id)
  end

  def load_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>News from Bruce</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
  <%= form_for @post do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <%= f.label :text %>
      <%= f.text_area :text %>
    </div>
    <div class="form-group">
      <%= f.label :category_id %>
      <%= f.text_field :category_id %>
    </div>
    <%= f.submit%>
  <% end %>

app/views/posts/edit.html.erb
<h1>Edit Post: "<%= @post.title %>"</h1>
<%= render partial: 'form' %>

app/views/posts/index.html.erb
<header>
  <h1><a href="http://localhost:3000/posts">News from Bruce</a></h1>
  <nav>
    <ul class="nav_links">
      <% @categories.each do |cat| %>
        <li><%= link_to cat.name, category_posts_path(category_handle: cat.handle), {:style=>'color:#FFF;'}%></li>
      <% end %>
    </ul>
  </nav>
  <% if user_signed_in? %>
    <ul class="links">
      <li>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, style: {color: 'white'}%>
      </li>
    </ul>
  <% else %>
  <ul class="links">
    <li><a href="<%= new_user_session_path %>">Login</a></li>
    <li><a href="<%= new_user_registration_path %>">Sing up</a></li>
  </ul>
  <% end %>
</header>
<body>
<div>
  <% if user_signed_in? %>
    <%= link_to "Create new post", new_post_path %>
  <% end %>
</div>
<div class="posts-container">
  <% @posts.each do |post| %>
    <div class="post">
      <%= link_to post , {:style=>'color:#000000;'} do %>
      <h3> <%= post.title %> </h3>
        <% end %>
      <p> <%= post.text %> </p>
      <%= link_to post.category.name, category_posts_path(category_handle: post.category.handle), {:style=>'color:#403A39;'} %>
      <p> <%= post.created_at %> </p>
    </div>
  <% end %>
</div>
</body>

app/views/posts/new.html.erb
<header>
  <h1><a href="http://localhost:3000/posts">News from Bruce</a></h1>
  <nav>
    <ul class="nav_links">
      <% @categories.each do |cat| %>
        <li><%= link_to cat.name, category_posts_path(category_handle: cat.handle), {:style=>'color:#FFF;'}%></li>
      <% end %>
    </ul>
  </nav>
  <% if user_signed_in? %>
    <ul class="links">
      <li>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, style: {color: 'white'}%>
    </ul>
  <% else %>
    <ul class="links">
      <li><a href="<%= new_user_session_path %>">Login</a></li>
      <li><a href="<%= new_user_registration_path %>">Sing up</a></li>
    </ul>
  <% end %>
</header>
<body>
  <div class="container">
    <h1>New Post</h1>
    <%= render partial: 'form' %>
  </div>
</body>

app/views/posts/show.html.erb
<header>
  <h1><a href="http://localhost:3000/posts">News from Bruce</a></h1>
  <nav>
    <ul class="nav_links">
      <% @categories.each do |cat| %>
        <li><%= link_to cat.name, category_posts_path(category_handle: cat.handle), {:style=>'color:#FFF;'}%></li>
      <% end %>
    </ul>
  </nav>
  <% if user_signed_in? %>
    <ul class="links">
      <li>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, style: {color: 'white'}%>
    </ul>
  <% else %>
    <ul class="links">
      <li><a href="<%= new_user_session_path %>">Login</a></li>
      <li><a href="<%= new_user_registration_path %>">Sing up</a></li>
    </ul>
  <% end %>
</header>
<body>
  <div class="content">
    <h1> <%= @post.title %> </h1>
    <div class="posts-container">
      <p> <%= @post.text %> </p>
    </div>
    <div class="additional">
      <p> <%= @post.category.name %> </p>
      <p> <%= @post.created_at %> </p>
    </div>
    <div class="buttons">
      <%= link_to 'Back to posts', posts_path, {:style=>'color:#000;'} %>
    </div>
    <div class="buttons">
      <%= link_to 'Edit', edit_post_path(@post.id), {:style=>'color:#000;'}   %>
    </div>
    <div class="buttons">
      <%= link_to 'Delete', post_path(@post.id), method: :delete, data: {confirm: "Are you sure?"} %>
    </div>
  </div>
  <div class="comments">
    <div class="comment_form">
      <h5>Leave your comment here</h5>
      <%= form_with model: [@post, @comment], local: true do |f| %>
        <%= f.text_area :body %>
        <%= f.submit "Comment" %>
      <% end %>
    </div>
    <div class="comments_show">
      <% @comments.each do |comment| %>
        [<%= comment.created_at.strftime("%I:%M %p") %>] <%= comment.user.username %>: <%= comment.body %>
        <br>
      <% end %>
    </div>
  </div>

</body>